base_url = "https://zummenix.github.io"

generate_feeds = true
compile_sass = true
minify_html = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
highlight_code = true
definition_list = true
external_links_target_blank = true

[link_checker]
external_level = "warn"

[extra]
socials = [
    { title = "Mail", link = "mailto:zummenix@gmail.com" , icon = "/socials/mail.svg" },
    { title = "GitHub", link = "https://github.com/zummenix" , icon = "/socials/github.svg" },
    { title = "Instagram", link = "https://instagram.com/zummenix" , icon = "/socials/instagram.svg" },
    { title = "LinkedIn", link = "https://www.linkedin.com/in/zummenix" , icon = "/socials/linkedin.svg" },
    { title = "Telegram", link = "https://t.me/zummenix" , icon = "/socials/tg.svg" }
]
